apiVersion: v1
kind: ResourceQuota
metadata:
  name: soc-quota
spec:
  hard:
    requests.cpu: "8"
    requests.memory: 16Gi
    limits.cpu: "12"
    limits.memory: 24Gi
    persistentvolumeclaims: "4"
