apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: soc
resources:
  - namespace.yaml
  - storageclass-gp3.yaml
  - wazuh-indexer.yaml
  - wazuh-manager.yaml
  - wazuh-analysis.yaml
  - cti-enricher.yaml
  - dashboard-and-soar.yaml
  - observability.yaml
  - falco-daemonset.yaml
  - security-controls.yaml
